name: ESLint

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: 
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install ESLint
      run: npm install -g eslint
    - name: Run ESLint
      run: eslint . --ext .js,.jsx,.ts,.tsx