name: Playwright Tests
on:
  push:
    branches: [iter-04-frontend]
  pull_request:
    branches: [iter-04-frontend]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        thread: ['main', 'server']
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm i
    - name: Run server
      if: ${{ matrix.thread == 'server' }}
      run: npm start
    - name: Install Playwright
      if: ${{ matrix.thread == 'main' }}
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      if: ${{ matrix.thread == 'main' }}
      run: npx playwright test
    - uses: actions/upload-artifact@v2
      if: ${{ matrix.thread == 'main' }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
