name: Playwright Tests
on:
  push:
    branches: [iter-04-frontend]
  pull_request:
    branches: [iter-04-frontend]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm i
    - name: Install Playwright
      run: npx playwright install --with-deps
    - name: Just start the server 4head
      run: npm start
    - name: Run Playwright tests
      with:
        build: npm start
        wait-on: 'http://localhost:3000'
        run: npx playwright test
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
